app/services/stock/controllers/stockController.js, app/services/stock/models/equityModel.js, app/services/stock/routes/stockRoutes.js, app/services/stock/scripts/populateTickers.js
I realized that we will often need to validate that a ticker is valid.
- Created the `equity/ticker/:ticker` endpoint to determine if the requested ticker is a valid ticker.
Returns object of `{ exists: true }` or `{ exists: false }` accordingly.
Example:
Requesting **AMZN**:
Requesting **BMZN**:
- Created `scripts/populateTickers.js` as a one-time execution to populate the database with all of the tracked tickers. Documents stored as `Ticker` schema, stored in the tickers collection.
=> Implement endpoint to check if a ticker is valid

frontend/.eslintrc.json, frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/styles/Login/Login.scss, frontend/src/styles/Registration/Registration.scss, frontend/src/styles/root.scss
Added some divs and styling to fix the navbar
=> Fix navbar covering site content

frontend/src/components/CreateLeague/CreateLeague.js
Small issues that prevented the application from running. Just need to merge this PR to prevent issues for everyone.
=> Fixed small issues that were not addressed for CreateLeague

frontend/src/components/CreateLeague/CreateLeague.js
Create league is now functional. There is frontend and backend form validation, the latter mainly for checking if league names are already in use.
=> Create league functionality

frontend/.eslintrc.json, frontend/package-lock.json, frontend/src/components/Home/Home.js, frontend/src/styles/Home/Home.scss
For some reason I think there was a a scss declaration that I made that seemed to cause a slight problem for the button on the stock symbol lookup page and also messed with the graphs on the home page. Also after pulling from the main branch last night there were some issues with being able to run the application so I added something in .eslintrc.json to help with that.
=> Addressing style issues and application frontend issues

frontend/src/components/NavigationBar/NavigationBar.js
Just fixed some small typos: class -> className.
=> Fix Navbar typos

app/services/league/controllers/leagueController.js, app/services/league/routes/leagueRoutes.js, frontend/src/App.js, frontend/src/components/IndividualStock/IndividualStock.js, frontend/src/components/NavigationBar/NavigationBar.js, frontend/src/components/Pages.js, frontend/src/components/Portfolio/Portfolio.js, frontend/src/components/Portfolio/Sections/Positions.js, frontend/src/styles/Portfolio/Portfolio.scss, frontend/src/styles/Portfolio/Positions.scss
Very basic - needs styling.
Using a temporary dropdown for the league selection.
=> Implement basic portfolio positions UI

app/services/league/controllers/leagueController.js, frontend/src/components/Trade/Trade.js
Merging into jscheire-trade.
Trade has limited working functionality, with basic validation for the form. I'll complete the portfolio and ticker information section tomorrow.
=> Implement trade form functionality

app/services/league/controllers/leagueController.js, app/services/league/controllers/tradeController.js, app/services/league/controllers/userController.js, app/services/league/models/leagueModel.js, app/services/league/models/portfolioModel.js, app/services/league/models/userModel.js, app/services/league/routes/leagueRoutes.js, app/services/league/routes/tradeRoutes.js, app/services/league/routes/userRoutes.js, app/services/stock/controllers/equityController.js, app/services/stock/index.js, app/services/stock/models/equityModel.js, app/services/stock/routes/equityRoutes.js, app/services/stock/scripts/populateTickers.js
=> Add comments

frontend/src/components/IndividualStock/IndividualStock.js, frontend/src/components/IndividualStock/Sections/StockGraph.js, frontend/src/components/IndividualStock/Sections/StockStatistics.js, frontend/src/styles/IndividualStock/IndividualStock.scss
Made some more changes:
- used fetch instead of axios
- added percent change
- x axis of graph now has dates 
- restructured
=> Individual Stock Page Fixes

app/services/league/routes/userRoutes.js, frontend/src/components/Home/Home.js, frontend/src/components/Login/Login.js, frontend/src/components/Trade/Trade.js
1) Navbar doesn't load on login: Definitely not the best fix, just a temporary fix that reloads the page after going to /home 
2) Trade button doesn't execute on first click: I think 'validated' was not changing state fast enough, as it was still false after being set to true. Please try and let me know if this works.
I also added a line to Home.js because I was getting the unused variable error for history.
=> Possible bug fixes

app/services/league/controllers/leagueController.js, app/services/league/models/portfolioModel.js, app/services/league/routes/userRoutes.js
Here I'm calculating and pulling data for the portfolio return and holding return respectively relative to the previous closing. Here is a sample response.
4/5:
```
{
"currentNetWorth": "513.65",
"cashAvailable": "109.70",
"closePercentChange": "-0.87",
"holdings": {
"amc": {
"quantity": 3,
"costBasis": "10.13",
"currentPrice": "10.61",
"totalValue": "31.83",
"totalChange": "1.44",
"percentChange": "0.05",
"equityName": "AMC Entertainment Holdings Inc",
"closePercentChange": "13.36"
},
"gme": {
"quantity": 2,
"costBasis": "179.96",
"currentPrice": "186.06",
"totalValue": "372.12",
"totalChange": "12.20",
"percentChange": "0.03",
"equityName": "Gamestop Corporation",
"closePercentChange": "-2.35"
}
},
"netWorth": "NaN"
}
```
4/6:
```
{
"currentNetWorth": "520.58",
"cashAvailable": …
```
=> Calculate percent change on the backend

app/services/league/controllers/tradeController.js
I think the left hand operand was a String; converted both to integers.
Should address issues with trade quantity, i.e., `1 + 1 = 11`.
=> Fix quantity parsing

app/services/league/routes/userRoutes.js, app/services/stock/controllers/equityController.js
Addresses #69
Filtered out null intraday prices. Falls back to openPrice in the statistics endpoint if all intraday prices are null. I haven't been able to test this case out yet because the markets haven't been open.
=> Fix null prices

frontend/src/components/News/News.js
I spent an hour thinking it was a promise error :(
Addresses #99
=> Fix news console errors

frontend/src/components/IndividualStock/IndividualStock.js, frontend/src/components/IndividualStock/Sections/StockStatistics.js
- took out bid, ask, day range, ex dividend
=> Remove Irrelevant Stock Stats

app/services/league/tasks/orderTask.js
Implemented stop buy and stop sell orders.
=> Stop orders

app/services/league/controllers/tradeController.js, app/services/league/tasks/orderTask.js, frontend/src/components/JoinLeague/JoinLeague.js, frontend/src/components/Trade/Trade.js
Implemented market sell orders and limit sell orders.
=> Sell orders

app/services/league/controllers/tradeController.js
Market sell was calculating the updated quantity incorrectly.
=> Fix sell bug

app/services/league/controllers/leagueController.js, frontend/src/components/Portfolio/Portfolio.js, frontend/src/components/Portfolio/Sections/PortfolioHistory.js, frontend/src/styles/Portfolio/PortfolioHistory.scss
Resolves #114 
Displays the transaction history as a list at the bottom of the user's portfolio page.
=> Implement transaction history in portfolio

app/services/league/tests/league.test.js, app/services/stock/routes/newsRoutes.js, app/services/stock/tests/news.test.js
Still need Tooltip tests and maybe AI tests?
=> Backend tests

app/services/league/tests/league.test.js, frontend/package.json, frontend/src/App.test.js, frontend/src/components/Ai/Ai.test.js, frontend/src/components/CentralizedLeague/CentralizedLeague.test.js, frontend/src/components/LeagueManagement/LeagueManagement.test.js, frontend/src/components/News/News.test.js, frontend/src/components/Portfolio/Portfolio.test.js, frontend/src/components/Summary/Summary.test.js, frontend/src/components/SymbolLookup/SymbolLookup.test.js
=> frontend testing for demo 2
